### ISSUE TITLE
Please, update your manual for KOBO

### ISSUE THREAD

**Issue by nekromoff** [poirier/cheat#4]
https://cheat.readthedocs.io/en/latest/kobo.html

Change sqlite3 setup to (___DeviceId has been added as column):
```
$ sqlite3 /media/usb0/.kobo/KoboReader.sqlite3
sqlite> INSERT INTO user values("00000000-0000-0000-0000-000000000000","00000000-0000-0000-0000-000000000000","MyDummyUser@dummy.com","MyDummyUser@dummy.com","000011");
sqlite> .quit
```
Also link to more up-to-date firmware downloads: https://pgaskin.net/KoboStuff/kobofirmware.html

**Comment by poirier** [comment]
Thanks, I've updated those items.
